06.26.19
enextus/new-test-guru pull request #1
Opened 2019-06-26 12:37 UTC by enextus

2019-06-26 22:30 UTC, psylone requested changes

2019-06-26 22:30 UTC, psylone commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
`@arr` не используется.

2019-06-26 22:30 UTC, psylone commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
`Test.where()` вернёт массив и этот массив запушится в `@arr`, а также встанет на место соответствующего элемента, поскольку мы используем `map`. В результате получится двумерный массив (массив в котором каждый элемент это тоже массив).

2019-06-26 22:30 UTC, psylone commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
Для каждого идентификатора (теста который проходил пользователь) будет отдельный запрос к базе данных, чего хотелось бы избежать.

Результат можно получить одним запросом с помощью соединения (`joins`). Тебе нужно сделать выборку из таблицы тестов и соединить её с `initiated_tests`, а потом выбрать строки у которых соответствуют уровень теста и идентификатор текущего пользователя. Условие соединения в `joins` можно написать вручную с помощью SQL выражения.

Проще всего сначала нарисовать процесс выборки на бумаге.

2019-06-26 22:30 UTC, psylone commented on app/models/test.rb
> +  def self.tests_listing_by_category_name(category_name)
`tests` из названия метода лучше исключить, поскольку мы уже в контексте модели тестов.

2019-06-26 22:30 UTC, psylone commented on app/models/test.rb
> +    ids = Category.where("title = :title", title: category_name).ids
```suggestion
    ids = Category.where(title: category_name).ids
```

2019-06-26 22:30 UTC, psylone commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
```suggestion
    Test.where(category_id: ids).order(title: :desc).pluck(:title)
```

2019-06-26 22:30 UTC, psylone commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
Здесь также стоит сделать с помощью соединения.

2019-06-27 01:43 UTC, enextus commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
```
class User < ApplicationRecord

  def tests_by_level(level)
    user_id = self.id
    ids_of_initiated_tests_of_this_user = InitiatedTest.where(user_id: user_id).pluck(:test_id)
    arr = []
    ids_of_initiated_tests_of_this_user.map do |id|
      arr << Test.where("id = :id AND level = :level", id: id, level: level)
    end
  end
end

```

2019-06-27 10:02 UTC, psylone commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
Да, но `arr` тоже не используется, эта локальная переменная не нужна, поскольку мы используем `map`, а он уже возвращает модифицированный массив.

2019-06-27 10:23 UTC, enextus commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
def tests_by_level(level)
    user_id = self.id
    InitiatedTest.where(user_id: user_id).pluck(:test_id).map do |id|
      Test.where("id = :id AND level = :level", id: id, level: level).first
    end
  end

2019-06-27 10:24 UTC, enextus commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
нужно использовать JOIN одним словом

2019-06-27 10:26 UTC, enextus commented on app/models/test.rb
> +  def self.tests_listing_by_category_name(category_name)
Да, логично

self.listing_by_category_name(category_name)

2019-06-27 10:29 UTC, enextus commented on app/models/test.rb
> +    ids = Category.where("title = :title", title: category_name).ids
def self.listing_by_category_name(category_name)
    ids = Category.where(title: category_name).ids
    Test.where(category_id: ids).order(title: :desc).pluck(:title)
  end

2019-06-27 10:32 UTC, enextus commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
```
  def self.listing_by_category_name(category_name)
    ids = Category.where(title: category_name).ids
    Test.where(category_id: ids).order(title: :desc).pluck(:title)
  end
```

в скринкасте говорилось, что нельзя допускать проникновение параметров напрямую в код из за опасности запуска вредоносного кода, в качестве решения, предлагалась такая конструкция

`("title = :title", title: category_name)`

2019-06-27 10:32 UTC, enextus commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
да, согласен

2019-06-27 11:10 UTC, enextus commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
```

SELECT tests.title
FROM categories
INNER JOIN tests
ON tests.category_id = categories.id AND categories.title = 'Frontend'
ORDER BY tests.title DESC;


# SELECT tests.title
# FROM categories
# INNER JOIN tests
# ON tests.category_id = categories.id AND categories.title = 'Frontend'
# ORDER BY tests.title DESC;
#              title
# --------------------------------
#  3. Test for category: Frontend
#  2. Test for category: Frontend
#  1. Test for category: Frontend
# (3 rows)

```

2019-06-27 11:11 UTC, enextus commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
вот так это должно выглядеть в SQL

2019-06-27 11:18 UTC, enextus commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
```
SELECT tests.title
FROM tests
INNER JOIN initiated_tests
ON initiated_tests.test_id = tests.id AND tests.level = 3
;


# SELECT tests.title
# FROM tests
# INNER JOIN initiated_tests
# ON initiated_tests.test_id = tests.id AND tests.level = 3
# ;
#              title
# --------------------------------
#  1. Test for category: Frontend
#  1. Test for category: Frontend
#  1. Test for category: Frontend
#  Test for category: Backend
#  1. Test for category: Frontend
#  Test for category: Backend
#  2. Test for category: Frontend
#  Test for category: Backend
#  2. Test for category: Frontend
# (9 rows)
```

2019-06-27 12:25 UTC, enextus commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
https://github.com/enextus/new-test-guru/commit/b3583927ad070ea8e4d3a72f7e2029790b4082fb

2019-06-27 12:25 UTC, enextus commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
https://github.com/enextus/new-test-guru/commit/b3583927ad070ea8e4d3a72f7e2029790b4082fb

2019-06-27 13:17 UTC, enextus commented on app/models/user.rb
> +      @arr << Test.where("id = :id AND level = :level", id: id, level: level)
```
  def tests_by_level(level)
      Test.joins("INNER JOIN initiated_tests ON initiated_tests.test_id = tests.id").where("level = :level", level: level).pluck(:title)
  end
```

2019-06-27 13:23 UTC, enextus commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
`    Test.joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_name", category_name: category_name).order(title: :desc).pluck(:title)`

2019-06-27 13:58 UTC, enextus commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
```
  def self.listing_by_category_title(category_title)
    Test.joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_title", category_title: category_title).order(title: :desc).pluck(:title)
  end
```

2019-06-27 17:52 UTC, psylone commented on app/models/test.rb
> +    Test.where("category_id = :category_id", category_id: ids).order(title: :desc).pluck(:title)
> в скринкасте говорилось, что нельзя допускать проникновение параметров напрямую в код из за опасности запуска вредоносного кода, в качестве решения, предлагалась такая конструкция
> 
> `("title = :title", title: category_name)`

Всё верно, так тоже безопасно: `where(title: category_name)`.

2019-06-27 17:54 UTC, psylone approved these changes

2019-06-27 17:54 UTC, psylone commented on app/models/user.rb
> +      Test.joins("INNER JOIN initiated_tests ON initiated_tests.test_id = tests.id").where("tests.level = :level", level: level).pluck(:title)
`pluck` здесь не нужен, по заданию необходимо возвращать именно массив тестов.

2019-06-27 19:56 UTC, enextus commented on app/models/user.rb
> +      Test.joins("INNER JOIN initiated_tests ON initiated_tests.test_id = tests.id").where("tests.level = :level", level: level).pluck(:title)
`      Test.joins("INNER JOIN initiated_tests ON initiated_tests.test_id = tests.id").where("tests.level = :level", level: level)`

2019-06-27 19:58 UTC, merged