07.05.19
enextus/new-test-guru pull request #4
Opened 2019-07-05 20:29 UTC by enextus

> 1. Определите scope-методы:
> 
>     для выбора правильных Ответов
>     Для выбора Тестов по уровню сложности:
>       простой (нулевой или первый уровень),
>            средний (со второго по четвёртый),
>            сложный (с пятого и выше). Значение положительной бесконечности можно получить с помощью константы Float::INFINITY
>     scope-метод по умолчанию для получения Категорий, отсортированных по названию в порядке возрастания
> 
> 
> 2. Используйте scope-методы вместо методов моделей, которые были определены в предыдущих заданиях
> 
> 3. Определите валидации данных:
> 
>     Наличие атрибутов title, body, email в соответствующих моделях
>     Уровень Теста может быть только положительным целым числом
>     Может существовать только один Тест с данным названием и уровнем
>     У одного Вопроса может быть от 1-го до 4-х ответов.

2019-07-05 22:46 UTC, psylone requested changes
Не забывай о том что если задаётся валидация на уникальность, также необходимо создать уникальный индекс в базе данных.

2019-07-05 22:46 UTC, psylone commented on app/models/answer.rb
> +  scope :correctly_answered, -> { where(correct: true) }
Поскольку скоупы часто вызываются в цепочке, лучше выбирать более короткие имена, например просто `correct`.

2019-07-05 22:46 UTC, psylone commented on app/models/test.rb
> +  scope :hard, -> { where(level: 5..+1.0/0.0) }
`Float::INFINITY`.

2019-07-05 22:46 UTC, psylone commented on app/models/test.rb
> +  scope :listing_by_category_title, -> (category_title) { joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_title", category_title: category_titl
Скоупы должны иметь возможность вызываться по цепочке, поэтому необходимо возвращать объект класса `ActiveRecord::Relation`.

2019-07-05 22:46 UTC, psylone commented on app/models/test.rb
> +  scope :listing_by_category_title, -> (category_title) { joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_title", category_title: category_titl
Также я бы сортировку убрал из скоупа и назвал его короче: `by_category`.

2019-07-05 22:46 UTC, psylone commented on app/models/test.rb
> +#
Всё лишнее необходимо удалить.

2019-07-05 22:46 UTC, psylone commented on app/models/user.rb
> +  validates :name, presence: true, uniqueness: true
Скорее всего, у пользователей могут быть одинаковые имена.

2019-07-05 22:46 UTC, psylone commented on app/models/user.rb
>        Test.joins("INNER JOIN tests_users ON tests_users.test_id = tests.id").where(level: level)
`tests.by_level(level)`.

2019-07-05 22:46 UTC, psylone commented on app/models/user.rb
>        Test.joins("INNER JOIN tests_users ON tests_users.test_id = tests.id").where(level: level)
(скоуп `by_level` нужно будет определить).

2019-07-05 22:46 UTC, psylone commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: true
> Может существовать только один Тест с данным названием и уровнем

Внимательней.

2019-07-05 22:46 UTC, psylone commented on db/migrate/20190705140042_add_not_null_constraint_userss_email.rb
> +    change_column_null :users, :email, false
Пока ты не смерджил пулл реквест, можно откатить предыдущую миграцию и в ней же в `add_column` указать опцию `null: false` и накатить её заново.

2019-07-06 08:28 UTC, enextus commented on app/models/test.rb
> +  scope :hard, -> { where(level: 5..+1.0/0.0) }
irb(main):001:0> +1.0/0.0
=> Infinity
irb(main):002:0> Float::INFINITY
=> Infinity
irb(main):003:0>

2019-07-06 08:29 UTC, enextus commented on app/models/answer.rb
> +  scope :correctly_answered, -> { where(correct: true) }
correct

2019-07-06 08:29 UTC, enextus commented on app/models/test.rb
> +  scope :hard, -> { where(level: 5..+1.0/0.0) }
Float::INFINITY

2019-07-06 08:33 UTC, enextus commented on app/models/test.rb
> +  scope :listing_by_category_title, -> (category_title) { joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_title", category_title: category_titl
`scope :by_category, -> (category_title) { joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_title", category_title: category_title) }`

2019-07-06 08:34 UTC, enextus commented on app/models/test.rb
> +#
ok

2019-07-06 08:40 UTC, enextus commented on app/models/user.rb
> +  validates :name, presence: true, uniqueness: true
`  validates :name, presence: true`

2019-07-06 09:07 UTC, enextus commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: true
```
  validate :validate_naming_by_the_same_level, on: :create

  private

  def validate_naming_by_the_same_level
    errors.add(:name, 'the same name by this level was found in db, please take a other name') if Test.where(title: test.title).where(level: test.level)
  end
```

2019-07-06 11:45 UTC, enextus commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: true
```
  validate :validate_titling_by_the_same_level, on: :create

  private

  def validate_titling_by_the_same_level
    errors.add(:base, 'the same title by this level was found in db, please take a other title') if Test.where(title: title).where(level: level).count.positive?
  end
```

2019-07-06 12:27 UTC, enextus commented on db/migrate/20190705140042_add_not_null_constraint_userss_email.rb
> +    change_column_null :users, :email, false
done

2019-07-06 12:35 UTC, enextus commented
> Не забывай о том что если задаётся валидация на уникальность, также необходимо создать уникальный индекс в базе данных.

```
class AddIndex < ActiveRecord::Migration[5.2]
  def change
    add_index :users, :email, unique: true
  end
end
```

2019-07-06 12:53 UTC, enextus commented on app/models/user.rb
>        Test.joins("INNER JOIN tests_users ON tests_users.test_id = tests.id").where(level: level)
`  scope :by_level, -> (level) { joins("INNER JOIN tests_users ON tests_users.test_id = tests.id").where(level: level) }`

2019-07-06 16:01 UTC, psylone requested changes

2019-07-06 16:01 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:base, 'the maximum quantity of answers (4) for one question was reached') if Answer.where(question_id: id).count >= 4
Было правильно, теперь ты ищешь все ответы, у которых `question_id` равно идентификатору текущего ответа, что не верно. Там должен быть атрибут `question_id`.

2019-07-06 16:01 UTC, psylone commented on app/models/test.rb
> +  validate :validate_titling_by_the_same_level, on: :create
Не, ну зачем использовать свою валидацию, достаточно встроенных.

2019-07-06 16:01 UTC, psylone commented on app/models/test.rb
> +  scope :by_category, -> (category_title) { joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_title", category_title: category_title) }
Используй ассоциацию в `joins`, если она объявлена, не нужно писать условие соединения вручную.

2019-07-06 16:01 UTC, psylone commented on app/models/test.rb
> +  scope :by_category, -> (category_title) { joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_title", category_title: category_title) }
Мне больше нравится вариант: `where(categories: { title: category_title })`.

2019-07-06 16:01 UTC, psylone commented on app/models/test.rb
> +  scope :by_level, -> (level) { joins("INNER JOIN tests_users ON tests_users.test_id = tests.id").where(level: level) }
Здесь нам нужно вытащить все тесты определённого уровня и только, пользователь здесь ни при чём.

2019-07-06 16:01 UTC, psylone commented on app/models/user.rb
>    def tests_by_level(level)
Должно быть так: `tests.by_level(level)`.

2019-07-06 16:01 UTC, psylone commented on app/models/test.rb
> +  validate :validate_titling_by_the_same_level, on: :create
Не увидел индекса в базе данных.

2019-07-06 16:01 UTC, psylone commented on app/models/test.rb
> +  validate :validate_titling_by_the_same_level, on: :create
При обновлении мы также не должны иметь возможность записать тест с таким же названием и уровнем (если такой тест уже есть в базе).

2019-07-06 17:30 UTC, enextus commented on app/models/answer.rb
> +    errors.add(:base, 'the maximum quantity of answers (4) for one question was reached') if Answer.where(question_id: id).count >= 4
```
  validate :validate_max_answers_quantity, on: :create

  private

  def validate_max_answers_quantity
    errors.add(:base, 'the maximum quantity of answers (4) for one question was reached') if Answer.where(question_id: question.id).count >= 4
  end
```

2019-07-06 18:06 UTC, enextus commented on app/models/test.rb
> +  validate :validate_titling_by_the_same_level, on: :create
`  validates :title, presence: true, uniqueness: { scope: :level, message: 'both title, level with same values should happen once per db' }`

2019-07-06 18:27 UTC, enextus commented on app/models/test.rb
> +  validate :validate_titling_by_the_same_level, on: :create
```
class AddIndexToTestTitle < ActiveRecord::Migration[5.2]
  def change
    add_index :tests, [:title, :level], unique: true
  end
end



CREATE TABLE example (
    a integer,
    b integer,
    c integer,
    UNIQUE (a, c)
);
```
Такое ограничение указывает, что сочетание значений перечисленных столбцов должно быть уникально во всей таблице, тогда как значения каждого столбца по отдельности не должны быть (и обычно не будут) уникальными.

2019-07-06 18:29 UTC, enextus commented on app/models/test.rb
> +  validate :validate_titling_by_the_same_level, on: :create
```
new_test_guru=# \d tests
                                         Table "public.tests"
   Column    |            Type             | Collation | Nullable |              Default              
-------------+-----------------------------+-----------+----------+-----------------------------------
 id          | bigint                      |           | not null | nextval('tests_id_seq'::regclass)
 title       | character varying           |           | not null | 
 level       | integer                     |           | not null | 0
 created_at  | timestamp without time zone |           | not null | 
 updated_at  | timestamp without time zone |           | not null | 
 category_id | bigint                      |           |          | 
 user_id     | bigint                      |           |          | 
Indexes:
    "tests_pkey" PRIMARY KEY, btree (id)
    "index_tests_on_title_and_level" UNIQUE, btree (title, level)
    "index_tests_on_category_id" btree (category_id)
    "index_tests_on_user_id" btree (user_id)
Foreign-key constraints:
    "fk_rails_cda342dc0a" FOREIGN KEY (category_id) REFERENCES categories(id)
    "fk_rails_e0c5eb5e4a" FOREIGN KEY (user_id) REFERENCES users(id)
Referenced by:
    TABLE "questions" CONSTRAINT "fk_rails_cb4b358d50" FOREIGN KEY (test_id) REFERENCES tests(id)

```

2019-07-06 18:39 UTC, enextus commented on app/models/test.rb
> +  validate :validate_titling_by_the_same_level, on: :create
```
Migrating to AddIndexToTestTitle (20190706180859)
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  ↳ bin/rails:9
  [1m[35m (1.4ms)[0m  [1m[35mCREATE UNIQUE INDEX  "index_tests_on_title_and_level" ON "tests"  ("title", "level")[0m
  ↳ db/migrate/20190706180859_add_index_to_test_title.rb:3
```

2019-07-06 23:57 UTC, enextus commented on app/models/test.rb
> +  scope :by_level, -> (level) { joins("INNER JOIN tests_users ON tests_users.test_id = tests.id").where(level: level) }
`  scope :by_level, -> (level) { where(level: level) }`

2019-07-06 23:58 UTC, enextus commented on app/models/user.rb
>    def tests_by_level(level)
`  scope :by_level, -> (level) { where(level: level) }`

2019-07-07 00:09 UTC, enextus commented on app/models/test.rb
> +  scope :by_category, -> (category_title) { joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_title", category_title: category_title) }
```
  def tests_by_level(level)
      Test.joins(:tests_users).where(level: level)
  end
```

2019-07-07 09:57 UTC, enextus commented on app/models/test.rb
> +  scope :by_category, -> (category_title) { joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title = :category_title", category_title: category_title) }
```
  belongs_to :category
joins(:category)
```

2019-07-07 10:29 UTC, enextus commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: true
```
irb(main):040:0> test = Test.new(title: "Test for category: DevOps, test code: 1992", level: 7, category_id: 1, user_id: 2)
=> #<Test id: nil, title: "Test for category: DevOps, test code: 1992", level: 7, created_at: nil, updated_at: nil, category_id: 1, user_id: 2>
irb(main):041:0> test.valid?
  Category Load (1.0ms)  SELECT  "categories".* FROM "categories" WHERE "categories"."id" = $1 ORDER BY "categories"."title" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Test Exists (0.7ms)  SELECT  1 AS one FROM "tests" WHERE "tests"."title" = $1 AND "tests"."level" = $2 LIMIT $3  [["title", "Test for category: DevOps, test code: 1992"], ["level", 7], ["LIMIT", 1]]
=> false
irb(main):042:0> test.errors.full_messages
=> ["Title and level with the corresponding values already exist in the db"]
irb(main):043:0>
```

2019-07-07 10:33 UTC, enextus commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: true
```
irb(main):051:0> test = Test.find(11)
  Test Load (0.7ms)  SELECT  "tests".* FROM "tests" WHERE "tests"."id" = $1 LIMIT $2  [["id", 11], ["LIMIT", 1]]
=> #<Test id: 11, title: "Test for category: DevOps, test code: 8785", level: 7, created_at: "2019-07-07 10:16:51", updated_at: "2019-07-07 10:16:51", category_id: 3, user_id: 2>
irb(main):052:0> test
=> #<Test id: 11, title: "Test for category: DevOps, test code: 8785", level: 7, created_at: "2019-07-07 10:16:51", updated_at: "2019-07-07 10:16:51", category_id: 3, user_id: 2>
irb(main):053:0> Test.find(14)
  Test Load (0.9ms)  SELECT  "tests".* FROM "tests" WHERE "tests"."id" = $1 LIMIT $2  [["id", 14], ["LIMIT", 1]]
=> #<Test id: 14, title: "Test for category: DevOps, test code: 9638", level: 7, created_at: "2019-07-07 10:16:51", updated_at: "2019-07-07 10:16:51", category_id: 3, user_id: 1>
irb(main):054:0> test.title = "Test for category: DevOps, test code: 9638"
=> "Test for category: DevOps, test code: 9638"
irb(main):055:0> test.save
   (0.4ms)  BEGIN
  Category Load (0.6ms)  SELECT  "categories".* FROM "categories" WHERE "categories"."id" = $1 ORDER BY "categories"."title" ASC LIMIT $2  [["id", 3], ["LIMIT", 1]]
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Test Exists (0.8ms)  SELECT  1 AS one FROM "tests" WHERE "tests"."title" = $1 AND "tests"."id" != $2 AND "tests"."level" = $3 LIMIT $4  [["title", "Test for category: DevOps, test code: 9638"], ["id", 11], ["level", 7], ["LIMIT", 1]]
   (0.4ms)  ROLLBACK
=> false
irb(main):056:0> test.errors.full_messages
=> ["Title and level with the corresponding values already exist in the db"]
irb(main):057:0> 
```

2019-07-07 21:59 UTC, psylone approved these changes

2019-07-07 21:59 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:base, 'the maximum quantity of answers (4) for one question was reached') if Answer.where(question_id: question.id).count >= 4
Лучше использовать атрибут `question_id`, тогда не нужно будет делать запрос в базу для получения объекта ответа.

2019-07-07 21:59 UTC, psylone commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: { scope: :level, message: 'and level with the corresponding values already exist in the db' }, on: [:create, :update]
В данном случае опция `on` не нужна. `create` + `update` = `save`, а валидация вызывается именно перед `save`.

2019-07-07 21:59 UTC, psylone commented on app/models/test.rb
> +  scope :simple, -> { where(level: 0..1) }
```suggestion
  scope :simple, -> { by_level(0..1) }
```

2019-07-07 21:59 UTC, psylone commented on db/migrate/20190706180859_add_index_to_test_title.rb
> +    add_index :tests, [:title, :level], unique: true
👍

2019-07-07 22:05 UTC, enextus commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: { scope: :level, message: 'and level with the corresponding values already exist in the db' }, on: [:create, :update]
ok

2019-07-07 22:07 UTC, enextus commented on app/models/test.rb
> +  scope :simple, -> { where(level: 0..1) }
ok

2019-07-07 22:09 UTC, enextus commented on app/models/answer.rb
> +    errors.add(:base, 'the maximum quantity of answers (4) for one question was reached') if Answer.where(question_id: question.id).count >= 4
ок

2019-07-07 22:10 UTC, merged